name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v4


    # Step 4: Start the MySQL database container (using Docker Compose)
    - name: Start the service using  Docker Compose
      run: docker compose -f docker_compose.yaml up -d 


    # Step 9: Test the /drift endpoint and log the output
    - name: Test /drift API
      run: |
        response=$(curl -s -H "x-api-key: thequickbrownfox" http://localhost:3000/drift)
        echo "Response from /drift: $response"

    # Step 10: Stop all services after the test
    - name: Stop Docker services
      run: docker compose -f docker_compose.yaml down
